name: CI

on:
  # Build on pushes to release branches
  push:
    branches: [v8]
  # Build on pull requests targeting release branches
  pull_request:
    branches: [v8]
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  build:
    name: Build, lint and test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npx ls-engines
      - run: npm run typecheck
      - run: npm run build
      - run: npm run lint -- --quiet
      - run: npm run coverage

  test:
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Run the testing suite on each major OS with the latest LTS release of Node.js
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [lts/*]
        # It makes sense to also test the oldest, and latest, versions of Node.js, on ubuntu-only since it's the fastest CI runner
        include:
          - os: ubuntu-latest
            # Test the oldest LTS release of Node that's still receiving bugfixes and security patches, versions older than that have reached End-of-Life
            node: lts/-1
          - os: ubuntu-latest
            # Test the actively developed version that will become the latest LTS release next October
            node: current
        # The `build` job already runs the testing suite in ubuntu and lts/*
        exclude:
          - os: ubuntu-latest
            # Test the oldest LTS release of Node that's still receiving bugfixes and security patches, versions older than that have reached End-of-Life
            node: lts/*
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node }}
      - run: npm i
      - run: npx ls-engines
      - run: npm run build
      - run: npm test
        # Only run the RSC testing suite if native `fetch` is available
      - run: node -e "fetch" && npm run test:react-server || true

  test-esm:
    name: Test ESM exports
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          # The testing suite uses the native test runner introduced in Node.js v18
          # https://nodejs.org/api/test.html
          node-version: lts/*
      - run: npm ci
      - run: npm run build
      - run: npm run test:esm
        # This test will run both in a CJS and an ESM mode in Node.js to ensure backwards compatibility
        name: Ensure pkg.exports don't break anything in modern Node.js envs
      - run: npm run test:esm:browser
        # This test is just ensuring the pkg.exports defined by 'browser' conditionals don't point to files that don't exist and have valid syntax (no CJS)
        # Please note that this test DOES support Node.js APIs, we need to test in a Cloudflare Worker v8 runtime, or Vercel Edge Runtime, to fully test e2e
        name: Test the 'browser' conditional using Node.js

  test-deno:
    name: Test Deno
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npm run build
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: npm run test:esm:deno
        name: Test that Deno can import `get-it`

  test-browser:
    name: Test Browser
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npm run test:browser -- run --coverage

  test-edge:
    name: Test Edge Runtime
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npm run test:edge-runtime -- run --coverage
